### ISSUE TITLE
Üres válasz php hibaüzenet miatt

### ISSUE THREAD

**Issue by pezsgo** [gabeeedev/to_remake#2]
Helló!

Klónoztam a to remake-et az oldalamra, és hibaüzenetet dob a php a keresésnél:

Fatal error: Uncaught Error: Call to undefined function split() in /to_remake/extension.php:24 Stack trace: #0 /to_remake/data.php(89): getDataTable('Kurzusnev@Kurzu...') #1 {main} thrown in /to_remake/extension.php on line 24

Remélem, tudtam segíteni!
Gábor

**Comment by gabeeedev** [comment]
Fogalmam sincs miért split van benne és hogy miért működik caesar-on, javítom máris, köszi.
